apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamhub-backend
  labels:
    app: streamhub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamhub-backend
  template:
    metadata:
      labels:
        app: streamhub-backend
    spec:
      containers:
      - name: backend
        image: <your-dockerhub-username>/streamhub-backend:latest # Replace with your Docker Hub image
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
