apiVersion: v1
kind: Service
metadata:
  name: streamhub-frontend-service
spec:
  selector:
    app: streamhub-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
